apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: backend-ns
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http

---

kind: Service
apiVersion: v1
metadata:
  name: hello
  namespace: frontend-ns
spec:
  selector:
    app: hello
    tier: backend
  type: ExternalName
  externalName: hello.backend-ns.svc.cluster.local
  ports:
  - port: 80
